Document: nebula
Title: Debian nebula Manual
Author: <insert document author here>
Abstract: This manual describes what nebula is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nebula/nebula.sgml.gz

Format: postscript
Files: /usr/share/doc/nebula/nebula.ps.gz

Format: text
Files: /usr/share/doc/nebula/nebula.text.gz

Format: HTML
Index: /usr/share/doc/nebula/html/index.html
Files: /usr/share/doc/nebula/html/*.html
